set_property PACKAGE_PIN T16 [get_ports {o_rgb[0]}]
set_property PACKAGE_PIN R16 [get_ports {o_rgb[1]}]
set_property PACKAGE_PIN U17 [get_ports {o_rgb[2]}]
set_property PACKAGE_PIN R17 [get_ports {o_rgb[3]}]
set_property PACKAGE_PIN T17 [get_ports {o_rgb[4]}]
set_property PACKAGE_PIN R19 [get_ports {o_rgb[5]}]
set_property PACKAGE_PIN R18 [get_ports {o_rgb[6]}]
set_property PACKAGE_PIN P18 [get_ports {o_rgb[7]}]
set_property PACKAGE_PIN R14 [get_ports {o_rgb[8]}]
set_property PACKAGE_PIN T14 [get_ports {o_rgb[9]}]
set_property PACKAGE_PIN P14 [get_ports {o_rgb[10]}]
set_property PACKAGE_PIN T15 [get_ports {o_rgb[11]}]
set_property PACKAGE_PIN P15 [get_ports {o_rgb[12]}]
set_property PACKAGE_PIN U14 [get_ports {o_rgb[13]}]
set_property PACKAGE_PIN P16 [get_ports {o_rgb[14]}]
set_property PACKAGE_PIN U15 [get_ports {o_rgb[15]}]
set_property PACKAGE_PIN V12 [get_ports {o_rgb[16]}]
set_property PACKAGE_PIN T10 [get_ports {o_rgb[17]}]
set_property PACKAGE_PIN W13 [get_ports {o_rgb[18]}]
set_property PACKAGE_PIN T11 [get_ports {o_rgb[19]}]
set_property PACKAGE_PIN U13 [get_ports {o_rgb[20]}]
set_property PACKAGE_PIN U12 [get_ports {o_rgb[21]}]
set_property PACKAGE_PIN V13 [get_ports {o_rgb[22]}]
set_property PACKAGE_PIN T12 [get_ports {o_rgb[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports clk]
#set_property PACKAGE_PIN U18 [get_ports clk]
#set_property PACKAGE_PIN J15 [get_ports rst_n]
#set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_bl]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_de]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_hs]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_vs]
set_property IOSTANDARD LVCMOS33 [get_ports o_rgb_clk]
set_property PACKAGE_PIN P19 [get_ports lcd_hs]
set_property PACKAGE_PIN N18 [get_ports lcd_bl]
set_property PACKAGE_PIN W19 [get_ports lcd_de]
set_property PACKAGE_PIN W18 [get_ports lcd_vs]
set_property PACKAGE_PIN T19 [get_ports lcd_rst_n]
set_property PACKAGE_PIN N17 [get_ports o_rgb_clk]






set_property PACKAGE_PIN T9 [get_ports i_pclk]
#set_property PACKAGE_PIN U5 [get_ports vsync]
set_property PACKAGE_PIN T5 [get_ports href]
set_property IOSTANDARD LVCMOS33 [get_ports href]
set_property IOSTANDARD LVCMOS33 [get_ports i_pclk]
#set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN V8 [get_ports {i_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_data[0]}]
set_property PACKAGE_PIN W8 [get_ports {i_data[6]}]
set_property PACKAGE_PIN W10 [get_ports {i_data[5]}]
set_property PACKAGE_PIN W9 [get_ports {i_data[4]}]
set_property PACKAGE_PIN U9 [get_ports {i_data[3]}]
set_property PACKAGE_PIN U8 [get_ports {i_data[2]}]
set_property PACKAGE_PIN W11 [get_ports {i_data[1]}]
set_property PACKAGE_PIN Y11 [get_ports {i_data[0]}]


create_clock -period 40.000 -name ov_cllk -waveform {0.000 20.000} -add [get_ports i_pclk]
create_clock -period 20.000 -name sysclk -waveform {0.000 10.000} -add [get_ports clk]


set_property PACKAGE_PIN U5 [get_ports vsyn]
set_property IOSTANDARD LVCMOS33 [get_ports vsyn]

