set_property PACKAGE_PIN T16 [get_ports {o_rgb[0]}]
set_property PACKAGE_PIN R16 [get_ports {o_rgb[1]}]
set_property PACKAGE_PIN U17 [get_ports {o_rgb[2]}]
set_property PACKAGE_PIN R17 [get_ports {o_rgb[3]}]
set_property PACKAGE_PIN T17 [get_ports {o_rgb[4]}]
set_property PACKAGE_PIN R19 [get_ports {o_rgb[5]}]
set_property PACKAGE_PIN R18 [get_ports {o_rgb[6]}]
set_property PACKAGE_PIN P18 [get_ports {o_rgb[7]}]
set_property PACKAGE_PIN R14 [get_ports {o_rgb[8]}]
set_property PACKAGE_PIN T14 [get_ports {o_rgb[9]}]
set_property PACKAGE_PIN P14 [get_ports {o_rgb[10]}]
set_property PACKAGE_PIN T15 [get_ports {o_rgb[11]}]
set_property PACKAGE_PIN P15 [get_ports {o_rgb[12]}]
set_property PACKAGE_PIN U14 [get_ports {o_rgb[13]}]
set_property PACKAGE_PIN P16 [get_ports {o_rgb[14]}]
set_property PACKAGE_PIN U15 [get_ports {o_rgb[15]}]
set_property PACKAGE_PIN V12 [get_ports {o_rgb[16]}]
set_property PACKAGE_PIN T10 [get_ports {o_rgb[17]}]
set_property PACKAGE_PIN W13 [get_ports {o_rgb[18]}]
set_property PACKAGE_PIN T11 [get_ports {o_rgb[19]}]
set_property PACKAGE_PIN U13 [get_ports {o_rgb[20]}]
set_property PACKAGE_PIN U12 [get_ports {o_rgb[21]}]
set_property PACKAGE_PIN V13 [get_ports {o_rgb[22]}]
set_property PACKAGE_PIN T12 [get_ports {o_rgb[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_rgb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN U18 [get_ports clk]
set_property PACKAGE_PIN J15 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_bl]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_de]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_hs]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_vs]
set_property IOSTANDARD LVCMOS33 [get_ports o_rgb_clk]
set_property PACKAGE_PIN P19 [get_ports lcd_hs]
set_property PACKAGE_PIN N18 [get_ports lcd_bl]
set_property PACKAGE_PIN W19 [get_ports lcd_de]
set_property PACKAGE_PIN W18 [get_ports lcd_vs]
set_property PACKAGE_PIN T19 [get_ports lcd_rst_n]
set_property PACKAGE_PIN N17 [get_ports o_rgb_clk]






set_property PACKAGE_PIN T9 [get_ports i_pclk]
set_property PACKAGE_PIN U5 [get_ports vsync]
set_property PACKAGE_PIN T5 [get_ports href]
set_property IOSTANDARD LVCMOS33 [get_ports href]
set_property IOSTANDARD LVCMOS33 [get_ports i_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN V8 [get_ports {i_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_data[0]}]
set_property PACKAGE_PIN W8 [get_ports {i_data[6]}]
set_property PACKAGE_PIN W10 [get_ports {i_data[5]}]
set_property PACKAGE_PIN W9 [get_ports {i_data[4]}]
set_property PACKAGE_PIN U9 [get_ports {i_data[3]}]
set_property PACKAGE_PIN U8 [get_ports {i_data[2]}]
set_property PACKAGE_PIN W11 [get_ports {i_data[1]}]
set_property PACKAGE_PIN Y11 [get_ports {i_data[0]}]


create_clock -period 40.000 -name ov_cllk -waveform {0.000 20.000} -add [get_ports i_pclk]
create_clock -period 20.000 -name sysclk -waveform {0.000 10.000} -add [get_ports clk]



create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list i_pclk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {inst_ova/inst_ova_read/i_data[0]} {inst_ova/inst_ova_read/i_data[1]} {inst_ova/inst_ova_read/i_data[2]} {inst_ova/inst_ova_read/i_data[3]} {inst_ova/inst_ova_read/i_data[4]} {inst_ova/inst_ova_read/i_data[5]} {inst_ova/inst_ova_read/i_data[6]} {inst_ova/inst_ova_read/i_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list inst_ova/inst_ova_read/href]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list inst_rgb_top/lcd_de]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list inst_ova/inst_ova_read/o_data_vld]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list inst_ova/inst_ova_read/o_fifo_work_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list inst_ova/inst_ova_read/rst_n]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list inst_ova/inst_ova_read/vsync]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 24 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {inst_rgb_top/i_rgb[0]} {inst_rgb_top/i_rgb[1]} {inst_rgb_top/i_rgb[2]} {inst_rgb_top/i_rgb[3]} {inst_rgb_top/i_rgb[4]} {inst_rgb_top/i_rgb[5]} {inst_rgb_top/i_rgb[6]} {inst_rgb_top/i_rgb[7]} {inst_rgb_top/i_rgb[8]} {inst_rgb_top/i_rgb[9]} {inst_rgb_top/i_rgb[10]} {inst_rgb_top/i_rgb[11]} {inst_rgb_top/i_rgb[12]} {inst_rgb_top/i_rgb[13]} {inst_rgb_top/i_rgb[14]} {inst_rgb_top/i_rgb[15]} {inst_rgb_top/i_rgb[16]} {inst_rgb_top/i_rgb[17]} {inst_rgb_top/i_rgb[18]} {inst_rgb_top/i_rgb[19]} {inst_rgb_top/i_rgb[20]} {inst_rgb_top/i_rgb[21]} {inst_rgb_top/i_rgb[22]} {inst_rgb_top/i_rgb[23]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list inst_rgb_top/i_data_vld]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list inst_ova/inst_ova_read/i_fifo_empty]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list inst_rgb_top/o_data_ready]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list inst_rgb_top/w_fifo_read_en]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
